name: release-CI

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Free disk space
        run: curl -s https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh | bash
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Quay IO
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ vars.QUAY_OAUTH_USERNAME }}
          password: ${{ secrets.QUAY_OAUTH_TOKEN }}
    
      - name: Build docker image and push to quay.io
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: quay.io/annefou/docker-jupytergis-notebook:${{ github.event.release.tag_name }}


